### ISSUE TITLE
concurrent store and load

### ISSUE THREAD

**Issue by magras** [vtyulb/AtomicSharedPtr#1] opened 2020-10-24 09:49 UTC
I believe that your implementation of `AtomicSharedPtr::store()` is unsafe because it ignores packed refcount. Imagine two threads:
* First thread enters `get()` function and increments packed refcount.
* Second thread enters `store()` and deletes value and control block.
* First thread resumes and tries to increment refcount inside deleted control block.

This scenario can be modeled with:
```c++
void atomic_shared_ptr_concurrent_store_load_test() {
    const auto threadCount = std::thread::hardware_concurrency();
    LFStructs::AtomicSharedPtr<int> sp(new int(0));
    std::vector<std::thread> threads;
    for (unsigned i = 0; i < threadCount/2; i++) {
        threads.emplace_back([&sp]{
            while (true)
                sp.store(new int(42));
        });
    }
    for (unsigned i = threadCount/2; i < threadCount; i++) {
        threads.emplace_back([&sp]{
            while (true)
                sp.get();
        });
    }
    for (auto &thread : threads) {
        thread.join();
    }
}
```

Output example:
```
AtomicSharedPtr: /home/magras/src/AtomicSharedPtr/src/atomic_shared_ptr.h:99: void LFStructs::SharedPtr<T>::unref(LFStructs::ControlBlock<T>*) [with T = int]: Assertion `before' failed.
malloc(): unsorted double linked list corrupted
```

**Comment by vtyulb** [comment] 2020-10-24 10:15
Yep, I think it's true. store() method was never used or tested. It's a kind of legacy from the times, when I thought that everything would be simple. Easiest way to fix the issue is to call internally compareExchange() in a store() method and drop the smart pointer afterwards. I'll add your test and fix problem later.

**Comment by vtyulb** [comment] 2020-10-24 22:01
fixed in https://github.com/vtyulb/AtomicSharedPtr/commit/ed5ac4a3a27f3d8a791ba55b718fc3850ea0c2bc

Thank you for the report and test! I was pretty sure, that no one will try to understand AtomicSharedPtr concept, so your issue was a pleasant surprise

**Closed** 2020-12-07 19:15 UTC
